### ISSUE TITLE
Menu is displayed out of the visible area

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [rasitayaz/flutter-pie-menu#31]
How can I adjust the menu to be inside the visible area, without moving the trigger button?

<img width="163" alt="image" src="https://user-images.githubusercontent.com/5072806/216261595-f22de6dd-5b60-4480-839d-cd9365420be8.png">

**Comment by rasitayaz** [comment]
This widget was not meant to be used as a floating action menu in the first place, and I'm afraid changing the angle of the menu items is not possible at the moment.

You can try other similar widgets like [circular_menu](https://pub.dev/packages/circular_menu) if they satisfy your needs.

However, I'll leave this issue open since this is actually a bug about the angle calculation system that I have implemented and it needs to be fixed. I can't say when but I'll definitely look into this.

**Comment by mariomurrent-softwaresolutions** [comment]
Hmm okay. The circular_menu library is not as nice as yours and not as easy to customize.

Cool thx - it's would also be okay if the menu is just rendered in the visible area :) For now I solved it, which putting the menu button in the center of the page.

**Comment by rasitayaz** [comment]
adda5c017a4ee7084fdca6c5a0dfb74694e62c55 fixes this issue, I will release an update soon.

**Comment by mariomurrent-softwaresolutions** [comment]
Amazing, thank you very much 😊
