### ISSUE TITLE
Is it possible to open menu through code?

### ISSUE THREAD

**Issue by realchrisparker** [rasitayaz/flutter-pie-menu#48]
Is it possible to open menu through code? I ask because I am working with DataTable2 and the generate code doesn't allow me to wrap a DataRow with a PieMenu.

**Comment by rasitayaz** [comment]
Currently not possible, but I'll leave this issue open if anyone is interested to implement this feature.

I think a controller-based approach would work.

**Comment by erecord** [comment]
Hey @rasitayaz, firstly thanks for this awesome package. It's a huge time saver and it works great.

I've created a PR to implement a simple controller-based approach. When you have some time, would you mind taking a look? Let me know if you'd prefer any changes or don't agree with the approach - I'm happy to discuss it.

In a future PR, I'd like to update the `ChangeNotifier` to a `ValueNotifier<Alignment>` so that a developer can specify where they'd like the tap be, instead always tapping the mid point. 

Let me me know what you think.

**Comment by realchrisparker** [comment]
Thank you team!
